name: Install and cache dependencies
author: Johannes L. Borresen
runs:
  using: composite
  steps:
    - name: Setup Node.js

      uses: actions/setup-node@v3.8.1
      with:
        node-version: "19"

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        run_install: false

    - name: Detect PNPM store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # Re-run dependency installation in case of cache misses.
    - name: Install dependencies
      shell: bash
      run: pnpm install