
name: Unit Tests
on:
  workflow_call:
    inputs:
      unused:
        type: boolean
        description: Unused, but you must define something to use workflow_call.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test